// <auto-generated />
using System;
using CRM.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809151055_AddPipelinesStagesAndDealsTablesAndRelationships")]
    partial class AddPipelinesStagesAndDealsTablesAndRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("821d5944-0d99-4c09-8c15-b215326f16a2"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "New York"
                        },
                        new
                        {
                            Id = new Guid("0088610b-1c8c-4ecd-8b8f-e0ce33c43e20"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = new Guid("f37ccf52-73d1-41e2-8e2f-68a6ca23b7d1"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "Chicago"
                        },
                        new
                        {
                            Id = new Guid("bcc8279c-ace7-493f-8d6d-4068bfbab187"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "Houston"
                        },
                        new
                        {
                            Id = new Guid("6d6bce59-8f2b-45a1-a3cf-b87a1fa84544"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "Phoenix"
                        },
                        new
                        {
                            Id = new Guid("a1abf398-d027-4870-bcda-631057e9591d"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "Philadelphia"
                        },
                        new
                        {
                            Id = new Guid("1d956265-f939-41a4-858e-ca1b89fac2e7"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "San Antonio"
                        },
                        new
                        {
                            Id = new Guid("642e9d3b-0446-462d-a274-614e43060933"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "San Diego"
                        },
                        new
                        {
                            Id = new Guid("203a3d68-fa7a-4cc0-9ab8-7fcc6a0cdad2"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "Dallas"
                        },
                        new
                        {
                            Id = new Guid("ea9fbf79-53a2-4a8b-9ba1-eaf9c288c286"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "San Jose"
                        },
                        new
                        {
                            Id = new Guid("be9e6d13-1d73-492d-a28b-a54049d34fee"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "Austin"
                        },
                        new
                        {
                            Id = new Guid("66673ebf-97e8-4ff7-940c-b9044d84d835"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "Jacksonville"
                        },
                        new
                        {
                            Id = new Guid("96f98ebf-826c-4f36-b27b-03bab2afa113"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "Fort Worth"
                        },
                        new
                        {
                            Id = new Guid("5579f22c-9b76-42a8-a4bd-fab8f45c4e52"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "Columbus"
                        },
                        new
                        {
                            Id = new Guid("3f721690-7919-4295-8481-4f6ac41bb921"),
                            Code = "",
                            CountryId = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            IsActive = true,
                            Name = "Charlotte"
                        },
                        new
                        {
                            Id = new Guid("cefe0767-484f-4ea8-9fe5-733b46cff5da"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = new Guid("4f9b6cc8-5576-475a-b088-498985e656bb"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = new Guid("603bc9c5-3c82-41f8-94f4-b69b63adea5d"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "İzmir"
                        },
                        new
                        {
                            Id = new Guid("4259c332-50a3-4c82-832c-9b57fc713bde"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Bursa"
                        },
                        new
                        {
                            Id = new Guid("19331d5c-9a11-492e-a854-dbaeff3ecb6f"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Adana"
                        },
                        new
                        {
                            Id = new Guid("5ba0f0d1-ab69-4aa7-8fad-d30203aaccdb"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Gaziantep"
                        },
                        new
                        {
                            Id = new Guid("d161cd9e-e4d9-4990-bf01-4cff8b8d4219"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Konya"
                        },
                        new
                        {
                            Id = new Guid("44aa8553-413e-4b76-bac0-62d55ee286e5"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Antalya"
                        },
                        new
                        {
                            Id = new Guid("49894086-5e32-4611-a8d8-4d6458a55d8a"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Mersin"
                        },
                        new
                        {
                            Id = new Guid("4e3ea7f4-5d32-4772-b7cc-34561a15aefe"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Kayseri"
                        },
                        new
                        {
                            Id = new Guid("aebae0b7-7909-4540-95c1-f2a4a243a317"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Samsun"
                        },
                        new
                        {
                            Id = new Guid("be759822-e3ea-4b94-9343-770bfc3b4243"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Eskişehir"
                        },
                        new
                        {
                            Id = new Guid("1dc11c27-0909-4492-b09f-bf6f1d4c6122"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Denizli"
                        },
                        new
                        {
                            Id = new Guid("ea2a1e7d-b0d8-4dcc-aa71-09da69438317"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Sakarya"
                        },
                        new
                        {
                            Id = new Guid("0568abe7-ec7d-474d-9048-2d339531bf4c"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Trabzon"
                        },
                        new
                        {
                            Id = new Guid("6788c496-0bba-4635-82da-af4590052aa8"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Malatya"
                        },
                        new
                        {
                            Id = new Guid("f0da3d2c-489c-46bd-92c1-798dd2c95e84"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Erzurum"
                        },
                        new
                        {
                            Id = new Guid("861f2ec4-cfae-4cca-adbf-997f594b8b54"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Van"
                        },
                        new
                        {
                            Id = new Guid("8df339bb-d6a9-46d8-9d9c-0c6ad1494e0a"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Aydın"
                        },
                        new
                        {
                            Id = new Guid("d0df355c-97a8-4df8-954f-51421080c1bc"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Balıkesir"
                        },
                        new
                        {
                            Id = new Guid("8d0e2826-254e-4d21-a2c1-24267befe436"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Kocaeli"
                        },
                        new
                        {
                            Id = new Guid("1f76975a-2b82-48ec-a49c-d1b9aa10989e"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Sivas"
                        },
                        new
                        {
                            Id = new Guid("07a91c4e-c934-429b-8df5-6702f0cd914f"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Kütahya"
                        },
                        new
                        {
                            Id = new Guid("332325b1-a6d8-453e-8b23-341bace22dab"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Aksaray"
                        },
                        new
                        {
                            Id = new Guid("4ddba39d-c99f-43ed-a87a-c40a5358f934"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Kırşehir"
                        },
                        new
                        {
                            Id = new Guid("7c4868e4-d950-432d-b5ab-5243007387d5"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Niğde"
                        },
                        new
                        {
                            Id = new Guid("1946c5c9-1918-4f01-b771-b0507bccad87"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Nevşehir"
                        },
                        new
                        {
                            Id = new Guid("37518f8c-4edc-49d1-9a4f-f7897adaed02"),
                            Code = "",
                            CountryId = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            IsActive = true,
                            Name = "Uşak"
                        },
                        new
                        {
                            Id = new Guid("2ecf7973-0591-43db-839d-85122da9d380"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = new Guid("25a6ddce-b444-4328-af59-6a2c3e06966b"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Hamburg"
                        },
                        new
                        {
                            Id = new Guid("4e40c7bb-8190-4aec-8c2d-519c08218462"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Münih"
                        },
                        new
                        {
                            Id = new Guid("259282bb-fa7a-43e9-b55e-cd5a6e7bbe38"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Köln"
                        },
                        new
                        {
                            Id = new Guid("f566dbba-1f6a-42a2-b93f-2f24111a7aac"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Frankfurt"
                        },
                        new
                        {
                            Id = new Guid("91f8e6ee-2809-46b0-bf42-c18960b5c96b"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Stuttgart"
                        },
                        new
                        {
                            Id = new Guid("63cd73bc-62ff-493c-bb2d-f52536d1d13e"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Düsseldorf"
                        },
                        new
                        {
                            Id = new Guid("bd1d490b-4818-425a-a08b-79f33faad0d0"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Dortmund"
                        },
                        new
                        {
                            Id = new Guid("709a09b7-5545-4f19-bf84-c7222a193762"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Essen"
                        },
                        new
                        {
                            Id = new Guid("ddbb6019-b778-49e5-859a-a1167fc61954"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Leipzig"
                        },
                        new
                        {
                            Id = new Guid("781e2dac-ac41-4b8b-9463-889a1e8766ac"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Bremen"
                        },
                        new
                        {
                            Id = new Guid("aa406209-fcf1-431d-aaf7-53ca4b246326"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Dresden"
                        },
                        new
                        {
                            Id = new Guid("f1132f1a-c96c-4d15-80f1-f16dbf1b76a9"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Hannover"
                        },
                        new
                        {
                            Id = new Guid("d132cdb6-5f6d-4402-a509-ef85f82ac0c0"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Nürnberg"
                        },
                        new
                        {
                            Id = new Guid("03456984-e0c9-4333-9762-8f2795bcd4aa"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Duisburg"
                        },
                        new
                        {
                            Id = new Guid("a7e795d5-7f69-4b6c-b86f-befd65a4c4cc"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Bochum"
                        },
                        new
                        {
                            Id = new Guid("81d7abc9-e37a-40da-882b-5a1b5fd44da2"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Wuppertal"
                        },
                        new
                        {
                            Id = new Guid("855cd093-f688-475a-9879-1d22548b1ad3"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Bielefeld"
                        },
                        new
                        {
                            Id = new Guid("9c27d03e-4b20-44ef-ab5b-b505daad655e"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Bonn"
                        },
                        new
                        {
                            Id = new Guid("3f9899cb-a03a-4a15-8482-d021b773db44"),
                            Code = "",
                            CountryId = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            IsActive = true,
                            Name = "Mannheim"
                        },
                        new
                        {
                            Id = new Guid("f7a3baf5-6dd9-4171-a993-4da9232d5c94"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = new Guid("46b2de2c-8dcd-4485-bb20-bef2214b2d02"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Marsilya"
                        },
                        new
                        {
                            Id = new Guid("d0a3935e-18df-496b-82fa-959dbd08a1f9"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Lyon"
                        },
                        new
                        {
                            Id = new Guid("ce02cf54-98b9-4b19-a135-64e777abd8cc"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Toulouse"
                        },
                        new
                        {
                            Id = new Guid("578151c6-4e76-4d41-8489-af8ce7b0d1cf"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Nice"
                        },
                        new
                        {
                            Id = new Guid("1eeab416-36f9-4243-ba86-e7466dab1147"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Nantes"
                        },
                        new
                        {
                            Id = new Guid("3fc8d333-6b4c-4a1e-8c9d-e521bcb48c78"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Strazburg"
                        },
                        new
                        {
                            Id = new Guid("8907022e-3df6-49f8-82c9-4dc6b1cf4615"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Lille"
                        },
                        new
                        {
                            Id = new Guid("997d87c4-26d5-424f-9519-6b9c06766950"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Rennes"
                        },
                        new
                        {
                            Id = new Guid("616cb9d3-e807-45a5-b006-2e34b421d97d"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Reims"
                        },
                        new
                        {
                            Id = new Guid("a7ee2d0d-4807-4ce1-82e4-20af30e6b74a"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Le Havre"
                        },
                        new
                        {
                            Id = new Guid("4e5fc982-4641-4ec2-b85c-33949b9b7366"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Saint-Étienne"
                        },
                        new
                        {
                            Id = new Guid("45aba4d7-d7e4-4dd7-b837-32bc98a49079"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Toulon"
                        },
                        new
                        {
                            Id = new Guid("8364063c-c2f6-4866-a2ef-21faad0b4099"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Grenoble"
                        },
                        new
                        {
                            Id = new Guid("f59491f9-1949-4652-919d-6de0bbd778bf"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Dijon"
                        },
                        new
                        {
                            Id = new Guid("1a391c42-5792-4fb6-a554-d007a3d14361"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Angers"
                        },
                        new
                        {
                            Id = new Guid("39569c67-b536-43b7-abcb-37ca622ef90e"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Nîmes"
                        },
                        new
                        {
                            Id = new Guid("a7287e8f-9131-4ce1-b68a-139d1626215f"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Villeurbanne"
                        },
                        new
                        {
                            Id = new Guid("4ae0ad6e-2875-4dca-af71-fe26fdc31499"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Clermont-Ferrand"
                        },
                        new
                        {
                            Id = new Guid("e85267ec-f437-4693-b516-dc08a174a6e4"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Le Mans"
                        },
                        new
                        {
                            Id = new Guid("c95e0848-3396-4d65-8a12-5decfe1904c9"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Aix-en-Provence"
                        },
                        new
                        {
                            Id = new Guid("6595a174-1ac5-4237-81af-42dbbd015b07"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Brest"
                        },
                        new
                        {
                            Id = new Guid("5e9a6eeb-e3f0-4a1d-a9b8-2adc5f500c6d"),
                            Code = "",
                            CountryId = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            IsActive = true,
                            Name = "Tours"
                        },
                        new
                        {
                            Id = new Guid("a0b5e21f-8381-4d72-959f-6bf68fc911de"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Londra"
                        },
                        new
                        {
                            Id = new Guid("8a0a6a77-fe06-43f4-b877-ac0b01e2c669"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Birmingham"
                        },
                        new
                        {
                            Id = new Guid("52ecad15-b70b-40f7-a9bd-0565af94ad7c"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Manchester"
                        },
                        new
                        {
                            Id = new Guid("506d6742-06c2-493c-8e38-27d8fc217545"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = new Guid("9846e683-7f10-4748-b998-91d50d211590"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Leeds"
                        },
                        new
                        {
                            Id = new Guid("1d259b43-3f3d-44e5-9e07-3b4ca1b34ffc"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Newcastle"
                        },
                        new
                        {
                            Id = new Guid("5ab988ec-f87f-4f43-ae8c-cf25ee072040"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Sheffield"
                        },
                        new
                        {
                            Id = new Guid("8285a86a-e310-4e6d-864d-fa0fc0bd2a00"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Bristol"
                        },
                        new
                        {
                            Id = new Guid("8ed3ff06-ed09-416f-9273-2e84c7d6ef6b"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Nottingham"
                        },
                        new
                        {
                            Id = new Guid("2dc8fd0a-db77-4f63-9b0b-92f119325748"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Leicester"
                        },
                        new
                        {
                            Id = new Guid("dcb3eb7f-9f2c-4e20-a669-830c8a821f35"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Coventry"
                        },
                        new
                        {
                            Id = new Guid("c41c269a-2b51-456a-877b-08f06d2db633"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Sunderland"
                        },
                        new
                        {
                            Id = new Guid("9e2cc3dc-d201-4e89-86e4-9558ee6afee3"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Bradford"
                        },
                        new
                        {
                            Id = new Guid("c2ca97d4-b1b5-4a9a-a3ad-d371bb0dbe05"),
                            Code = "",
                            CountryId = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            IsActive = true,
                            Name = "Belfast"
                        });
                });

            modelBuilder.Entity("CRM.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IndustryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsappUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("X_Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DeletedById");

                    b.HasIndex("IndustryId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SourceId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.ContactStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("OrganizationId");

                    b.ToTable("ContactStages", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("45bfd61d-9433-4471-9465-bd1baa24b7ef"),
                            Code = "US",
                            IsActive = true,
                            Name = "Amerika Birleşik Devletleri",
                            PhoneCode = "+1"
                        },
                        new
                        {
                            Id = new Guid("132144df-5225-4408-826d-fcc378c0f74f"),
                            Code = "TR",
                            IsActive = true,
                            Name = "Türkiye",
                            PhoneCode = "+90"
                        },
                        new
                        {
                            Id = new Guid("bfc27405-1111-42d8-8888-1292364f5c42"),
                            Code = "DE",
                            IsActive = true,
                            Name = "Almanya",
                            PhoneCode = "+49"
                        },
                        new
                        {
                            Id = new Guid("72f3a930-add3-484a-af1a-9a9d61785ec4"),
                            Code = "FR",
                            IsActive = true,
                            Name = "Fransa",
                            PhoneCode = "+33"
                        },
                        new
                        {
                            Id = new Guid("1b1da575-eabe-4d8c-8c29-daa4ab7f5432"),
                            Code = "GB",
                            IsActive = true,
                            Name = "İngiltere",
                            PhoneCode = "+44"
                        });
                });

            modelBuilder.Entity("CRM.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("87f3e85d-c0b0-4b0b-961f-6211c88fb412"),
                            Code = "USD",
                            Name = "Amerikan Doları",
                            Status = true,
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("d1f3e85d-c0b0-4b0b-961f-6211c88fb413"),
                            Code = "EUR",
                            Name = "Euro",
                            Status = true,
                            Symbol = "€"
                        },
                        new
                        {
                            Id = new Guid("e2f3e85d-c0b0-4b0b-961f-6211c88fb414"),
                            Code = "GBP",
                            Name = "İngiliz Sterlini",
                            Status = true,
                            Symbol = "£"
                        },
                        new
                        {
                            Id = new Guid("f3f3e85d-c0b0-4b0b-961f-6211c88fb415"),
                            Code = "TRY",
                            Name = "Türk Lirası",
                            Status = true,
                            Symbol = "₺"
                        });
                });

            modelBuilder.Entity("CRM.Domain.Entities.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpectedClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("Value")
                        .HasColumnType("money")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DeletedById");

                    b.HasIndex("Id");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SourceId");

                    b.HasIndex("StageId");

                    b.HasIndex("PipelineId", "StageId");

                    b.ToTable("Deals", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Industry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Industries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("97a92ec2-44cb-4c51-bde8-30e59c80f136"),
                            Name = "Perakende E-Ticaret",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("4e2fe32d-d574-46d2-89b9-6dc4b5aba976"),
                            Name = "Gayrimenkul",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("04333d8d-f676-41d9-b4e7-b9ded1eee930"),
                            Name = "Üretim",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("2363cc8c-4f2b-4104-a375-6f5f66235e33"),
                            Name = "Sağlık",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("77b7e8e7-a371-49d6-8db1-895baaaa991e"),
                            Name = "Turizm",
                            Status = true
                        });
                });

            modelBuilder.Entity("CRM.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IndustryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DeletedById");

                    b.HasIndex("IndustryId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SourceId");

                    b.HasIndex("StageId");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Pipeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("Id");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Pipelines", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0694ec4c-8e49-4a0e-b93f-79d41fe88bfa"),
                            Name = "Super Admin"
                        },
                        new
                        {
                            Id = new Guid("21f2f8f1-84e2-44d6-847b-b81ebabc2b8b"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("c443f0b1-08dd-4ed7-b72d-4f0255557acd"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("CRM.Domain.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Sources", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("Id");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PipelineId");

                    b.ToTable("Stages", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.City", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Company", b =>
                {
                    b.HasOne("CRM.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Currency", "Currency")
                        .WithMany("Companies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRM.Domain.Entities.Industry", "Industry")
                        .WithMany("Companies")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRM.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "Owner")
                        .WithMany("Companies")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Source", "Source")
                        .WithMany("Companies")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CRM.Domain.ValueObjects.PhoneNumber", "AlternatePhone", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AlternatePhone");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("CRM.Domain.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Email");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("CRM.Domain.ValueObjects.PhoneNumber", "Fax", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Fax");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("CRM.Domain.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Phone");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("AlternatePhone");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("CreatedBy");

                    b.Navigation("Currency");

                    b.Navigation("DeletedBy");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Fax");

                    b.Navigation("Industry");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Organization");

                    b.Navigation("Owner");

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Contact", b =>
                {
                    b.HasOne("CRM.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("CRM.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("CRM.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CRM.Domain.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsOne("CRM.Domain.ValueObjects.PhoneNumber", "Mobile", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Mobile");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsOne("CRM.Domain.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Phone");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("City");

                    b.Navigation("Company");

                    b.Navigation("Country");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Mobile")
                        .IsRequired();

                    b.Navigation("ModifiedBy");

                    b.Navigation("Organization");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("CRM.Domain.Entities.ContactStage", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("CRM.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("CRM.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Deal", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("CRM.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("CRM.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("CRM.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Pipeline", "Pipeline")
                        .WithMany("Deals")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Stage", "Stage")
                        .WithMany("Deals")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("CreatedBy");

                    b.Navigation("Currency");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Organization");

                    b.Navigation("Owner");

                    b.Navigation("Pipeline");

                    b.Navigation("Source");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Lead", b =>
                {
                    b.HasOne("CRM.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("CRM.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("CRM.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("CRM.Domain.Entities.Industry", "Industry")
                        .WithMany("Leads")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("CRM.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.ContactStage", "ContactStage")
                        .WithMany("Leads")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CRM.Domain.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("LeadId");

                            b1.ToTable("Leads");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.OwnsOne("CRM.Domain.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Phone");

                            b1.HasKey("LeadId");

                            b1.ToTable("Leads");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.Navigation("City");

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("ContactStage");

                    b.Navigation("Country");

                    b.Navigation("CreatedBy");

                    b.Navigation("Currency");

                    b.Navigation("DeletedBy");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Industry");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Organization");

                    b.Navigation("Owner");

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Pipeline", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("CRM.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("CRM.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Source", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("CRM.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("CRM.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Stage", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("CRM.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("CRM.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Pipeline", "Pipeline")
                        .WithMany("Stages")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Organization");

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("CRM.Domain.Entities.User", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("CRM.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Company", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("CRM.Domain.Entities.ContactStage", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Currency", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Industry", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Pipeline", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Source", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Stage", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("CRM.Domain.Entities.User", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
